Sprint 2
Tenutes/middle.messenger.praktikum.yandex pull request #2
Opened 2021-09-10 15:27 UTC by Tenutes

Второй спринтик. Впервые познакомился с Typescript.
- добавлен ESLint
- добавлен Prettier
- добавлен Typescript
- подготовлена основа для тестов на Jest
- Добавлена валидация всех форм
- Обновлена верстка компонентов

2021-09-11 17:52 UTC, nickchamel requested changes
Привет! В целом все отлично, видно что уже работал! Хорошая типизация кода. По структуре и организации кода работа не совсем похожа на MVC приложение, хотя это прописано в задании. Но там нет четких условий как это следует делать, поэтому это остается на твое усмотрение.
Но самое главное, чего я у тебя не вижу, так это реализации:
![image](https://user-images.githubusercontent.com/28347933/132954412-0315f1f8-5335-48a7-813b-daa1685c1099.png)
Тут уже конкретно в курсе описано как это сделать :) задание есть задание. Я на всякий случай спрошу можно ли мне будет принять твою реализацию, а пока работу возвращаю.

2021-09-11 17:52 UTC, nickchamel commented on src/common/Fetch/Fetcher.ts
> +const HTTPTransport: IHTTPTransport = {
можно сделать по аналогии классом, имплементирующим интерфейс, и сделать экспорт экземпляра

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +  }
Если нет формы то вернется `{}`? Как то нелогично немного

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +    const fields: FormElement[] = Array.from(this.form.querySelectorAll('input:not([type=hidden]), textarea, select'));
А вообще для значений проще пользоваться https://learn.javascript.ru/formdata

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +    const passwords: FormElement[] = fields.filter(field => field.name.startsWith('password'));
Пример: пришел другой разработчик на твой проект и назвал филд `pass`, сколько ему понадобится времени чтобы понять почему код не работает из-за названия филда?

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +    const mainPasswordField = passwords.find(({ name }: HTMLInputElement) => name === 'password');
Здесь и ниже тоже сильная завязака на нейминге (захардкожено). Это "bad practice"

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +      label && label.remove();
для лучшей читаемости лучше писать 
```
if (label) {
  label.remove();
}
```
А вообще уже давненько можно использовать optional chaining
`label?.remove()`

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +    }
Этот класс выглядит как некий агрегатор для всех форм, лучше соблюдать модульность и логику каждой формы держать в своем модуле.
У меня вот к примеру был проект в котором были формы на несколько экранов (по 200-300 филдов)
Я вот представить не могу что было бы с кодом, если бы я писал код в таком стиле :)

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +    const label = document.createElement('label');
для ошибки лучше использовать например `span`.
Тэг `label` обладает свойствами доступности и обрабатывается браузерами по особенном. Если кликнуть по лейблу у которого есть `for`, то инпут для которого является этот лейбл получит фокус.

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +    return label;
Вообще это выглядит как отдельный компонент ошибки если честно, у которого может быть свой шаблон и тп

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Sender.ts
> +      console.log(e);
Вот интересно как будет выглядеть твой код, если например это был запрос на регистрацию и здесь пришли ошибки о том что в поле пароля и емейла есть ошибки.
Если делать реализацию Блока, то будет компонент формы, который отрендерит свой шаблон, и при клике сам же отправит запрос на бэк, а получив ошибки он просто обновит свои пропсы - эти изменения подхватят его чайлды (филды формы) и тоже обновят свои пропсы, тем самым запустив процесс ререндеринга своего шаблона (каждый филд своего шаблона, и все это "автоматически"), после чего в UI под каждым филдом появится соответствующая ошибка. А все что нам для этого нужно было сделать - это написать `setProps({ submissionErrors })` к примеру. Потому что такова реализация класса Block (который нужно было сделать по заданию)

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Validate.ts
> +      return Validate.isEmailValid(input.value);
Выглядит сложно поддерживаемо. А что если у каждого инпута будут свои правила прописаны для валидации? И определяться это будет в шаблоне.
То есть например на логине выводим 2 филда, емейл и пароль - и прокидываем им в пропсы каждому свою регулярку грубо говоря, или массив с регулярками, или массив с функциями валидации, - тогда здесь мы может просто достать у инпута его валидации и прогнать по каждой из них его значение.

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/helpers.ts
> +  });
На каждый филд вешаешь по 2 обработчика. А где эти обработчики удаляются? Вот юзер перейдет на другой роут, там не будет формы вообще, а значит обработчики нужно удалить. В компонентом подходе это решается очень просто, на уровне компонента

2021-09-11 17:52 UTC, nickchamel commented on src/common/Store/Store.ts
> +  },
А смысл этого?) Есть приватная пропса, ты делаешь ее публичной. Этот код аналогичен:
```
state: {}
```

2021-09-11 17:52 UTC, nickchamel commented on src/helpers.ts
> +  });
Необязательно делать экспорт функции. Можно просто здесь оставить
```
Handlebars.registerHelper...
Handlebars.registerHelper...
```
а в индексе `import './helpers';`

2021-09-11 17:52 UTC, nickchamel commented on src/pages/chat-list/module.ts
> +};
Ререндерить вообще по хорошему должен роутер. В идеале если у тебя будут в адресной строке айдишники чатов `/chats/...`, и при обновлении страницы роутер будет отображать страницу чата, а она в свою очередь делать запрос на бэк за данными этого чата.

2021-09-11 17:52 UTC, nickchamel commented on src/partials.ts
> +  Handlebars.registerPartial('chat-form', ChatFormPartial);
Паршалы лучше регистрировать каждый в своем модуле, чтобы сохранить модульность и не исполнять код, который не нужен (например если мы на странице логина, то нам не нужны ни чаты ни настройки и тп)
Пример. модуль страницы логина - login.hbs, login.ts, login.scss.
В login.ts регистрируем паршал логина.
В нем нам нужны инпуты, а значит мы можем в login.ts `import 'components/input'` (.ts)
А инпут это тоже по хорошему полноценный модуль с input.ts, input.hbs и тд
И в input.ts мы регаем паршал инпута. Таким образом сохраняеться модульность и используется только то что необходимо в данный момент (то есть оптимизация по памяти)

2021-09-11 17:52 UTC, nickchamel commented on src/common/Registry/Registry.ts
> +const Registry: IRegistry = {
где-то классы, где-то объекты. лучше в одном стиле писать

2021-09-11 17:52 UTC, nickchamel commented on src/common/Form/Validate.ts
> +    const regExp = new RegExp(/^(\+7|7|8)?[\s\-]?\(?[489][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{2}[\s\-]?[0-9]{2}$/gi);
нет смысле создавать регулярки при кадом вызове методов класса. Их можно вынести в константы

2021-09-12 07:44 UTC, Tenutes commented on src/common/Form/Validate.ts
> +    const regExp = new RegExp(/^(\+7|7|8)?[\s\-]?\(?[489][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{2}[\s\-]?[0-9]{2}$/gi);
Хорошо, переделаю

2021-09-12 07:45 UTC, Tenutes commented on src/common/Registry/Registry.ts
> +const Registry: IRegistry = {
В классах я намереваюсь создавать неск. экземпляров. с Константами - один. Тянуть и так имеющийся singleton ввиде const я не хотел)

2021-09-12 07:46 UTC, Tenutes commented on src/partials.ts
> +  Handlebars.registerPartial('chat-form', ChatFormPartial);
Хорошо, сделаю. О таких 'микро-оптимизациях' в текущем приложении не задумывался.

2021-09-12 07:47 UTC, Tenutes commented on src/pages/chat-list/module.ts
> +};
Как раз до реализации роутера, делающего ререндер без перезагрузки я акцентировал на том, что пока рендерлю нужное ручками) Постараюсь переделать

2021-09-12 07:48 UTC, Tenutes commented on src/helpers.ts
> +  });
Согласен.

2021-09-12 07:49 UTC, Tenutes commented on src/common/Form/Form.ts
> +    const mainPasswordField = passwords.find(({ name }: HTMLInputElement) => name === 'password');
Долго думал, как внести эту проверку паролей в Валидатор, а не в модуль, ничего лучше не пришло. Переделаю логику валидатора и уберу это

2021-09-12 07:51 UTC, Tenutes commented on src/common/Form/Form.ts
> +    const fields: FormElement[] = Array.from(this.form.querySelectorAll('input:not([type=hidden]), textarea, select'));
Просили в консоль вывести объект с данными - сделал так :)
Если `FormData` можно создать и отправить, то в консоли будет пустой объект. Делать доп логику с `.entries` и выдачей - не стал. Поэтому такая реализация сделана намерено под задачи этого спринта.

2021-09-12 07:53 UTC, Tenutes commented on src/common/Form/Form.ts
> +  }
Вообще, такого кейса не будет, ибо еще в конструкторе при отсутствии формы вылетит Error, эта проверка сделана лишь для Typescript, который по-умолчанию "не верит" разработчику.

2021-09-12 07:54 UTC, Tenutes commented on src/common/Fetch/Fetcher.ts
> +const HTTPTransport: IHTTPTransport = {
Решил сделать без обертки `Singletone`, т.к. с константой в этом нет необходимости.
А так ли это плохо, когда нек. реализация на классах, а нек. на константах?
Разве это не подчеркивает намерения? Классы - создаем экземпляры, константы - единственный экземляр

2021-09-12 09:24 UTC, Tenutes commented on src/common/Form/Form.ts
> +  }
Хотя, если после создания экземпляра кто-то удалит форму из разметки, то тогда да, ее не будет. Но не значит ли это, что форма - пуста (ее нет, данных, тоже,  нет).

2021-09-12 14:50 UTC, nickchamel commented on src/common/Fetch/Fetcher.ts
> +const HTTPTransport: IHTTPTransport = {
Ты можешь экспорить класс, а можешь экспортить экземпляр класса `export default new HTTPTransport()` - это и будет синглтон.
Ничего плохого нет, как минимум лучше писать в одном стиле, а так же классы как минимум задел на масштабируемость, потому что позволят использовать все преимущества ООП, ты сможешь пользоваться наследованием, например, или модификаторами доступа. В 3 спринте например будут АПИ сервисы, которые должны быть синглтонами, но они могут наследоваться например от общего класса...

2021-09-12 14:52 UTC, nickchamel commented on src/common/Form/Form.ts
> +    const fields: FormElement[] = Array.from(this.form.querySelectorAll('input:not([type=hidden]), textarea, select'));
насколько я помню у тебя несколько мест где ты делаешь подобные вещи, те дублируешь код, это можно офрмить в небольшой хелпер и переиспользовать, например
```
export function getFormData(form) {
  const formData = new FormData(form);
  const result = {};

  for (const [key, value] of formData.entries()) {
    result[key] = value;
  }

  return result;
}

```

2021-09-12 16:00 UTC, Tenutes commented on src/common/Form/Form.ts
> +    const fields: FormElement[] = Array.from(this.form.querySelectorAll('input:not([type=hidden]), textarea, select'));
Не, метод для получения данных с форм один -в классе Form, но вот использую я его на всех формах, это да.
В следующем спринте, с подключением API переделать это на FormData - дело 10 минут и столько же - тестов. Так что пока все это сделано, опять же повторюсь, только для быстрого вывода в консоль)
Но все равно спасибо!

2021-09-13 10:36 UTC, Tenutes commented on src/common/Fetch/Fetcher.ts
> +const HTTPTransport: IHTTPTransport = {
Хорошо, переделал :)

2021-09-13 17:10 UTC, Tenutes commented on src/common/Form/Form.ts
> +    const passwords: FormElement[] = fields.filter(field => field.name.startsWith('password'));
Ууууууххх, переписал я всю валидацию, чую, намуууудриииил)

2021-09-13 18:01 UTC, Tenutes commented on src/common/Form/Form.ts
> +    const label = document.createElement('label');
Я примерно на такое и рассчитывал, вдруг (по какой-то причине), что-то с отображением ошибки (не там отобразилась), нажал - фокус на связанном поле

2021-09-13 18:02 UTC, Tenutes commented on src/common/Form/Form.ts
> +    return label;
Вынес, пока с начальной логикой, пока не потребовались шаблоны

2021-09-13 18:04 UTC, Tenutes commented on src/common/Form/Validate.ts
> +      return Validate.isEmailValid(input.value);
Переделал полностью эту логику.

2021-09-13 18:05 UTC, Tenutes commented on src/common/Form/helpers.ts
> +  });
Пока происходит полная перезагрузка - обработчики не остаются висеть, в будущем при добавлении роутера  это место будет найдено)

2021-09-13 18:08 UTC, Tenutes commented on src/common/Form/Sender.ts
> +      console.log(e);
К сожалению, я так не сумел разобраться за это время, как добавить реактивности в handlebars без ререндеринга всего компонента. Есть только идея иметь блоки с id="button" (к примеру), где впоследствии потом заменять этот блок на кнопку, иметь в компоненте ссылку на этот блок и при смене пропса - перерисовывать. Но появляется другой вопрос, связанный с состоянием, ибо получается, что для отдельно взятой кнопки, ссылки надо хранить его отдельно? Ибо при общем состоянии (как сейчас), при изменении любого prop - будет ререндерится весь компонент. Это пока бегло, к чему пришел, но, скорее всего, я не прав)

2021-09-14 18:27 UTC, nickchamel approved these changes
Привет! Отлично поработал, молодец :) оставил тебе еще немного комментиков...
Работу принимаю, успехов в дальнейшем!

2021-09-14 18:27 UTC, nickchamel commented on src/common/Block/Block.ts
> +    this.eventBus = () => eventBus;
можно просто `this.eventBus = new EventBus();`

2021-09-14 18:27 UTC, nickchamel commented on src/common/Block/Block.ts
> +    this._registerEvents(eventBus);
вообще листенеры должны чиститься перед рендером (ререндером) и регистрироваться после него.
Это входит в жизненный цикл компонента. Он же может заапдейтиться - значит разметка (ДОМ) вероятнее всего поменяется, что-то может уйти что-то добавится, соответсвенно какие-то ивенты уйдут, какие-то навешаются.
Логика должны быть примерно такая:
- removeEvents
- html = this.render()
- если есть чайлд-компоненты, можно здесь заменять подготовленные для них контейнеры на их срендеренный контент (как пример)
- this._elem.append(html)
- registerEvents

2021-09-14 18:27 UTC, nickchamel commented on src/common/Block/Block.ts
> +    const _this = this;
это можно избежать, если использовать далее стрелочные функции

2021-09-14 18:27 UTC, nickchamel commented on src/common/Validator/constants.ts
> +export const loginRegExp = new RegExp(/^(?=[a-zA-Z\-_\d]+[a-zA-Z\-_]+|[a-zA-Z\-_]+[a-zA-Z\-_\d]+)[a-zA-Z\-_\d]{3,20}$/);
именовать можно как и остальные константы, у самого вроде в CODESTYLE даже написано)

2021-09-14 18:27 UTC, nickchamel commented on src/common/Validator/types.d.ts
> +  error: ValidationError | null;
Если нет жесткой необходимости именно в null, а достаточно будет и undefined, то можно писать:
```
...
messageTemplate?: VALIDATOR_ERROR_CODES_NAMES;
...
error?: ValidationError;
...
```

2021-09-14 18:27 UTC, nickchamel commented on src/common/Router/types.d.ts
> +  currentPage: Route | undefined;
`_currentPage: Route | undefined;`
можно сократить
`_currentPage?: Route;`

2021-09-14 18:27 UTC, nickchamel commented on src/components/Button/button.ts
> +    registerPartials(partials);
Этот компонент будет потенциально создаваться множество раз, а значит каждый раз будет регистрироваться паршал. Можно регистрацию вынести перед объявлением компонента, и в остальных файлах если мы импортим button.ts, то его паршал будет зарегистрирован, а по скольку это будет отдельный модуль то он еще и отработает 1 раз, то есть паршал зарегистрируется 1 раз, а в других местах где тоже будет импорт Button он более не будет регистрироваться. Это все некритично и вообще хбс по факту помоему смотрит если он уже зареган то ничего не делает, но как минимум это просто логичней, и функций меньше вызывается, и конструктор чище, ну в таком духе...

2021-09-14 18:27 UTC, nickchamel commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Может стоит лучше типизировать стор, чтобы уже сразу было известно, что `Store.state.chatList` имеет тип `ChatProps[]`, чтобы не пришло везде такое писать

2021-09-14 18:27 UTC, nickchamel commented on src/common/Validator/Validator.ts
> +        success = (<HTMLInputElement>this).checked;
Я для примера тебе оставлю как максимально просто и лаконично сделать сами функции валидации (берем value, прогоняем через функцию, получаем либо сообщение об ошибке, либо undefined если все ок)
```
export const required = value => value || (typeof value === 'number' && !Number.isNaN(value)) ? undefined : 'Required';

export const requiredArray = value => (Array.isArray(value) && !isEmpty(value)) ? undefined : 'Required';

export const mortgageTerm = value => value && value > 600 ? 'Mortgage Term must be less or equal than 600.' : undefined;

export const greaterThan = number => value => value > number ? undefined : `Value must be grater than ${number}`;

export const toWarn = value => value ? undefined : 'Required';

export const number = (value) => {
  if (!value && value !== 0) return undefined;
  return (value && !Number.isNaN(value) ? undefined : 'Must be a number');
};

export const mortgageRate = value => (value && value < 999.99 ? undefined : 'Must be less then 999.99');

export const creditScore = value => ((value <= 900 && value >= 300) || !value || Number.isNaN(value) ? undefined : 'Must be between 300 and 900');

export const futureDate = value => moment(value).diff(moment()) < 0 ? 'Must be future date' : undefined;

export const furureFromNextMonthDate = value => (moment(value).diff(moment().add(1, 'month')) < 0 ? 'Must be future date' : undefined);

export const maskedMoreThanZero = value => ((value <= 0) || (Number.isNaN(value)) ? 'Must be more than 0' : undefined);

export const moreThanZero = value => (value < 0 ? 'Must be more than null' : undefined);
```

2021-09-14 19:36 UTC, Tenutes commented on src/common/Block/Block.ts
> +    this.eventBus = () => eventBus;
Сделаем

2021-09-14 19:39 UTC, Tenutes commented on src/common/Validator/constants.ts
> +export const loginRegExp = new RegExp(/^(?=[a-zA-Z\-_\d]+[a-zA-Z\-_]+|[a-zA-Z\-_]+[a-zA-Z\-_\d]+)[a-zA-Z\-_\d]{3,20}$/);
у меня в голове константы подразделяются на два типа:
1. прям константы-константы ;D (прим. const ABC = 'ABC', USER_ROLE_ADMIN = 'admin', ROLES =[USER_ROLE_ADMIN, ....])
2. и недоконстанты: это вот эти, что в примере выше, что это что-то типа экземпляров какого-то класса, какие-то выражения, что не знаю, рука не поднимается переводить в верхний регистр :(.

Надо мне как-то переосмыслить это.

2021-09-14 19:40 UTC, Tenutes commented on src/common/Validator/types.d.ts
> +  error: ValidationError | null;
Т.к. с Typescript первые недели (не оч его люблю из Vue - на нем с ним больно очень), то сначала столкнулся с тем, что когда писал ?: - у меня иногда ругалось на то, что я не передал/обхявил это св-во, что вызывало недопонимание и я добавлял null.

2021-09-14 19:41 UTC, Tenutes commented on src/common/Router/types.d.ts
> +  currentPage: Route | undefined;
Хорошо

2021-09-14 19:42 UTC, Tenutes commented on src/components/Button/button.ts
> +    registerPartials(partials);
Вообще, тут регистрация паршиала просто не нужна даже. Я ее уберу, ибо нигде на проекте не используется этот паршиал. Поэтому в их необходимость просто отпала, все перешло на обычный импорт шаблонов. Поэтому, удалю это просто.

2021-09-14 19:44 UTC, Tenutes commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Мне как-то не нравится типизировать ОБЩИЙ стор и добавлять в него возможное появление chatList (ибо то только на странице  с чатами). 
Есть ли смысл в такой типизации? Может, есть другое решение? Может, через какое-то расширение интерфейса сторы, (Я не знаю хорошие практики в TS :( )
Если нет, то так и сделаю.

2021-09-14 19:47 UTC, Tenutes commented on src/common/Validator/Validator.ts
> +        success = (<HTMLInputElement>this).checked;
Я пытался это как-то элегантно сделать через привязку контекста с инпутом (как в случае с equalsTo), в общем что-то новое попробовать.
За набор функций огромное спасибо!

2021-09-14 19:50 UTC, Tenutes commented on src/common/Block/Block.ts
> +    this._registerEvents(eventBus);
Понял, принял, осознал :)
Пока нет никакой реактивности 'натуральной' с подменой и регистрацией child у компонента (ибо пока у меня щаблоны возвращают строку, а не node (вроде, так можно), то не стал доделывать всю эту структуру. А так да, из теорию все это помним. Хуки жизненного цикла из Vue помним, любим (не скорбим).

2021-09-14 19:51 UTC, Tenutes commented on src/common/Block/Block.ts
> +    this.eventBus = () => eventBus;
Спасибо вам за все комментарии и что показали мне, что мой код в отдельных местах - какашка, давно я не получаю такой ОС :)

2021-09-14 21:07 UTC, nickchamel commented on src/common/Block/Block.ts
> +    this._registerEvents(eventBus);
Да из строки можно ДОМ сделать, можешь ознакомиться
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

2021-09-14 21:09 UTC, nickchamel commented on src/common/Validator/constants.ts
> +export const loginRegExp = new RegExp(/^(?=[a-zA-Z\-_\d]+[a-zA-Z\-_]+|[a-zA-Z\-_]+[a-zA-Z\-_\d]+)[a-zA-Z\-_\d]{3,20}$/);
константа, она и в африке константа) то что не меняется.
есть просто объявления const как замена var, там по конвенции camelCase...

2021-09-14 21:10 UTC, nickchamel commented on src/common/Validator/types.d.ts
> +  error: ValidationError | null;
хз, `?` значит опционал, то есть наоборот можно не передавать

2021-09-14 21:11 UTC, nickchamel commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Конечно есть смысл. Стор всегда будет иметь определенныц интерфейс. Не будет же такого, что изначально там нет свойства `user`, а потом мы его добавляем в рантайме.. Просто будет `user?: User`, то же самое и с chatList)

2021-09-14 21:13 UTC, nickchamel commented on src/common/Validator/Validator.ts
> +        success = (<HTMLInputElement>this).checked;
так лучше как раз value передавать, а не HTMLElement, this и тп. Лучше стараться максимально упрощать функции

2021-09-15 07:17 UTC, Tenutes commented on src/common/Block/Block.ts
> +    this._registerEvents(eventBus);
Почитаю, в следующем спринте применю тогда уже :) Спасибо

2021-09-15 07:18 UTC, Tenutes commented on src/common/Validator/constants.ts
> +export const loginRegExp = new RegExp(/^(?=[a-zA-Z\-_\d]+[a-zA-Z\-_]+|[a-zA-Z\-_]+[a-zA-Z\-_\d]+)[a-zA-Z\-_\d]{3,20}$/);
Не, второй вариант просто как замена меня не устраивает :)
Буду переходить везде на один стиль

2021-09-15 07:19 UTC, Tenutes commented on src/common/Validator/types.d.ts
> +  error: ValidationError | null;
Ну если еще встречу такое - буду разбираться в чем дело, может, там и мой косяк вовсе был)

2021-09-15 07:20 UTC, Tenutes commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Хммм. То есть я правильно понял, что при разрастании приложения interface state будет так же разрастаться вот так и это не плохо? Ладненько, сделаем :)

2021-09-15 07:21 UTC, merged

2021-09-15 21:36 UTC, nickchamel commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Ну в смысле, если новая фича появилась, например, добавили нотификации юзеров. То изначально в сторе не было `userNotifications`, а с фичой добавили и так далее, но в рантайме то стор не обрастает новыми свойствами, нет такого, что сделали запрос - и на успехе разрастается стор...

2021-09-16 06:21 UTC, Tenutes commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Не, ну про рантайм понятно-то, я имею ввиду следующее. 
Получается, что мы типизируем общий стор всего приложения, а не состояние отдельных модулей, подключаемые в него. Просто, как мне казалось, при довольно больших размерах приложения эта типизация общего стора может разрастись очень широко, поэтому думал, что это плохо.

2021-09-16 08:44 UTC, nickchamel commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Что значит модули, подключаемые в него?) Стор это по сути объект, который мы заполняем данными. Если этот объект заранее типизировать то будет проще работать (больше подсказок, меньше ошибок), вот и все

2021-09-16 10:08 UTC, Tenutes commented on src/pages/chat-list/module.ts
> +    const chat = (<ChatProps>(<unknown>Store.state)).chatList.find(({ id }) => id === chatId);
Ну это State конкретного модуля (Чатлист, Логин, Регистрация и т.п.). Вашу позицию я понял, буду придерживатся)