Sprint 3
Tenutes/middle.messenger.praktikum.yandex pull request #3
Opened 2021-10-08 08:19 UTC by Tenutes

Что сделано:
- Обновлена логика рендера, роутинга, стора
- Написаны тесты на основные модули, используя JEST
- Добавлена работа с API Yandex
- Доверстаны макеты
- Настроен ререндер "по запросу"

2021-10-08 19:30 UTC, nickchamel requested changes
Привет! Поработал на славу)) молодец. Много всего, тестов так вообще. Все аккуратно выглядит. По самой работе есть недочеты:

Если в форме есть ошибки то после введения данных они не исчезают
![image](https://user-images.githubusercontent.com/28347933/136614800-05f23568-4e1e-4b95-a81e-43da9df5983c.png)

Создать чат не получатеся и после обновления страницы он тоже не появляетя
![image](https://user-images.githubusercontent.com/28347933/136614928-bd3b051d-e403-48c0-ab43-1f4655703e23.png)

Апдейт профиля не работает
![image](https://user-images.githubusercontent.com/28347933/136615005-9878c1bb-4e2c-4b5c-915e-20ce90798f14.png)
Аватарку тоже можно поправить (пропорции искажены)

Это необходимо поправить, а так отписал тебе еще рекомендаций. Работу пока вернул

2021-10-08 19:30 UTC, nickchamel commented on src/api/AuthAPI.ts
> +export type UserData = Omit<SignupData, 'password'> & { id: number; avatar: string; display_name: string };
Семантически UserData от SignupData немного неверно. Для лучшей поддержки лучше иметь полную модельку юзера и уже ее омитить/пикать и тп

2021-10-08 19:30 UTC, nickchamel commented on src/api/AuthAPI.ts
> +  update: undefined;
Зачем описывать в базовом классе эти методы, если они не во всех дочерних будут?)
Ты сначала с помощью `extends BaseAPI` как бы говоришь "Этот класс должен имплементить create, read... в их соответствии с базовым классом", а потом костылишь их в undefined :)
Так то да - далеко не во всех "апихах" будет CRUD

2021-10-08 19:30 UTC, nickchamel commented on src/api/ChatAPI.ts
> +    return this.http.put('/users', data);
В некоторых методах типизация отсутствует, неплохо было бы тоже сделать

2021-10-08 19:30 UTC, nickchamel commented on src/common/Block/Block.ts
> +  cdmTimeout: NodeJS.Timeout | null;
таймоут и интервал просто число возращают

2021-10-08 19:30 UTC, nickchamel commented on src/common/Block/Block.ts
> +    return this.element!;
Выглядит прям вот непонятно)
Если есть элемент и родитель его документ-фрагмент, то ждем след итерацию ивентлупа и смотрим если родитель не равен документ-фрагменту то эмитим CDM..

И далее если нет this.element то тоже эмитим CDM.
По идее component did mount как раз означает, что компонент уже смонтирован, то есть присутствует в ДОМе, а значит this.element точно должен быть.

А так же сама функция getContent означает взять контент, а не запускать таймеры дидмаунты и прочее, то есть либо контент есть, либо его нет.

2021-10-08 19:30 UTC, nickchamel commented on src/common/helpers.ts
> +    if (maxWait > 0 && maxWait !== Infinity && !maxTimeout) {
Так у тебя `maxWait` по дефолту ставится в Infinity. То есть если не прокинуть в опциях то это условие никогда не выполнится

2021-10-08 19:30 UTC, nickchamel commented on src/components/AddUserPopup/index.ts
> +            const users = await UserController.searchUsers({ login: searchString });
Если промис может завершиться с ошибкой то нужна обработка

2021-10-08 19:30 UTC, nickchamel commented on src/components/AddUserPopup/index.ts
> +        const currentUsers = (searchResult.props as SearchResultProps).result;
можно this.refs типизировать с помощью дженериков, тогда не надо будет в каждом компоненте во многих местах писать type assertion `as` примерно так
![image](https://user-images.githubusercontent.com/28347933/136609873-95622ae4-a1ef-4376-8626-b3a908d01f97.png)
Тут же типизируются пропсы и тебе не нужно будет писать `this.props as PopupProps`

2021-10-08 19:30 UTC, nickchamel commented on src/components/AddUserPopup/index.ts
> +          if (typeof props?.onClose === 'function') {
пропсы ведь не опционал, onClose опционал

2021-10-08 19:30 UTC, nickchamel commented on src/components/ChangeImagePopup/index.ts
> +        const files = (e?.target as HTMLInputElement)?.files as FileList;
e тут тоже не опционал

2021-10-08 19:30 UTC, nickchamel commented on src/components/ChangeImagePopup/index.ts
> +        }
В интерфейсе пропсов уже прописано что onClose это функция, значит тут не нужно проверка на это.
Можно просто проверить есть ли значение, либо использовать опционал
```
props.onClose?.();
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#optional_chaining_with_function_calls

2021-10-08 19:30 UTC, nickchamel commented on src/components/ChatForm/index.ts
> +    this.element!.addEventListener('submit', (this.props as ChatFormProps).onSubmit);
У тебя вот как раз из-за того что элемента может не быть ТС подсвечивает.
В таком случае правильней будет использовать `?` а не `!`
`?` это замена `if` то есть 
```
if (this.element) {
  this.element.addEvent...
}
```
А знаком `!` ты просто ТС игнорируешь по сути и все. От ошибки в рантайме он не спасет!

2021-10-08 19:30 UTC, nickchamel commented on src/components/ChatList/index.ts
> +        }
А если чат не будет создан?) Я потому и говорю что обработка ошибок всегда нужна.
А у тебя контроллеры ошибки дальше не пробрасывают. В UI просто не произойдет ничего и пользователь никак не поймет об этом

2021-10-08 19:30 UTC, nickchamel commented on src/components/ChatUser/index.ts
> +        (this.props as ChatUserProps).onChatDelete(e, (this.props as ChatUserProps).chat.id);
Типизируй пропсы :)
(пример выше писал)

2021-10-08 19:30 UTC, nickchamel commented on src/index.ts
> +  const user = await AuthController.fetchUser();
При переходам по роутам каждый раз фетчится юзер?
Может все-таки на старте приложения сделать запрос, проверить аутентифицирован ли юзер и засетить isAuth = true куда-нибудь. А потом уже от этого отталкиваться (делать запрос или нет)

2021-10-08 20:22 UTC, Tenutes commented on src/api/AuthAPI.ts
> +export type UserData = Omit<SignupData, 'password'> & { id: number; avatar: string; display_name: string };
Хорошо, посмотрю, что можно сделать.

2021-10-08 20:22 UTC, Tenutes commented on src/common/Block/Block.ts
> +  cdmTimeout: NodeJS.Timeout | null;
Хм, вроде бы, тс ругался, если я просто number ставил, попробую еще раз тогда

2021-10-08 20:22 UTC, Tenutes commented on src/api/ChatAPI.ts
> +    return this.http.put('/users', data);
Сделаем

2021-10-08 20:23 UTC, Tenutes commented on src/api/AuthAPI.ts
> +  update: undefined;
Окей, просто уберу все, кроме констуктора

2021-10-08 20:24 UTC, Tenutes commented on src/common/Block/Block.ts
> +    return this.element!;
Тут в большинстве своем ,все это из-за handlebars (он не создаем контент из пустого шаблона, поэтому не создается эелемент - из-за этого эмичу cdm), например, на logout. Попробуй переписать

2021-10-08 20:27 UTC, Tenutes commented on src/common/helpers.ts
> +    if (maxWait > 0 && maxWait !== Infinity && !maxTimeout) {
Тут идея была именно в том, чтобы при infinity - не было ограничения :) Попробую тогда как-то переделать.

2021-10-08 20:28 UTC, Tenutes commented on src/components/AddUserPopup/index.ts
> +            const users = await UserController.searchUsers({ login: searchString });
Эта обработка у меня в Контроллере ведь. Там она и выводится потом в верстку.

2021-10-08 20:29 UTC, Tenutes commented on src/components/AddUserPopup/index.ts
> +        const currentUsers = (searchResult.props as SearchResultProps).result;
Хм, попробую, так как с ТСом впервые работаю, не до конца понимаю принцип работы дженериков. Спасибо за подсказку!

2021-10-08 20:31 UTC, Tenutes commented on src/components/ChatList/index.ts
> +        }
Хм, попробую отловить какую-нибудь ошибку, ибо я даже не знаю, какая может придти и куда ее выводить потом.

2021-10-08 20:31 UTC, Tenutes commented on src/components/ChatUser/index.ts
> +        (this.props as ChatUserProps).onChatDelete(e, (this.props as ChatUserProps).chat.id);
Yep

2021-10-08 20:33 UTC, Tenutes commented on src/index.ts
> +  const user = await AuthController.fetchUser();
Попробую, но единственная проверка на логин юзера - его фечнуть. Думаю, уберу перед каждым, сделаю на старте, а так там запрос и так 401 будет отдавать - попробую какой-то interceptor для xhr сделать, чтоб при 401 он выкидывал на логин.

2021-10-08 20:35 UTC, Tenutes commented on src/api/AuthAPI.ts
> +export type UserData = Omit<SignupData, 'password'> & { id: number; avatar: string; display_name: string };
По поводу ошибок - посмотрю, на локале и при запуске через express их не было (по ошибке вижу, что почему-то айдишника у формы нет). Так же и с чатом, все создавалось, даже с другом болтали через него :)

2021-10-09 14:35 UTC, Tenutes commented on src/common/Block/Block.ts
> +  cdmTimeout: NodeJS.Timeout | null;
Да, ТС ругается на number: S2322: Type 'Timeout' is not assignable to type 'number'.

2021-10-09 14:43 UTC, nickchamel commented on src/common/Block/Block.ts
> +  cdmTimeout: NodeJS.Timeout | null;
Так это не ТС ругается
https://www.typescriptlang.org/play?#code/G4QwTgBCBcEHYFcC2AjApmA3AKFJFsAzgC5gCWcA5jtiBALwSFrEAqZSaA9gsQBR8AlAwB8EAN4BfADQQADIJooGTFu049+Q0RJnzF2IA

2021-10-09 14:45 UTC, nickchamel commented on src/index.ts
> +  const user = await AuthController.fetchUser();
Интерсептор в идеале да!

2021-10-09 14:47 UTC, nickchamel commented on src/common/Block/Block.ts
> +  cdmTimeout: NodeJS.Timeout | null;
А мож и ТС, вот так еще можно `ReturnType<typeof setTimeout>`, просто пишем фронт приложение а типы из ноды это как-то не комильфо)

2021-10-09 15:48 UTC, Tenutes commented on src/components/ChangeImagePopup/index.ts
> +        const files = (e?.target as HTMLInputElement)?.files as FileList;
Сделано.

2021-10-09 15:48 UTC, Tenutes commented on src/components/ChangeImagePopup/index.ts
> +        }
Сделано.

2021-10-09 15:49 UTC, Tenutes commented on src/components/ChatForm/index.ts
> +    this.element!.addEventListener('submit', (this.props as ChatFormProps).onSubmit);
Да, в курсе, просто опять же, тс не доверяет мне, что там будет элемент, а он создается всегда, кроме страницы logout. Сделано.

2021-10-09 15:49 UTC, Tenutes commented on src/components/AddUserPopup/index.ts
> +          if (typeof props?.onClose === 'function') {
Сделано.

2021-10-09 15:51 UTC, Tenutes commented on src/components/AddUserPopup/index.ts
> +        const currentUsers = (searchResult.props as SearchResultProps).result;
<img width="1090" alt="Снимок экрана 2021-10-09 в 18 50 59" src="https://user-images.githubusercontent.com/34067613/136665466-cbd901df-7e17-4a62-9af3-5847ab03c772.png">
Пока застрял на вот этом, никак не получается это дотипизировать, буду думать)

2021-10-09 16:03 UTC, Tenutes commented on src/common/Block/Block.ts
> +  cdmTimeout: NodeJS.Timeout | null;
Тут я уже решил, взял не просто setTimeout, а window.setTimeout, чтоб он понял, что не из ноды беру :)

2021-10-09 17:14 UTC, Tenutes commented on src/components/AddUserPopup/index.ts
> +        const currentUsers = (searchResult.props as SearchResultProps).result;
В общем, тут вообще никак не получается, пришлось везде `any` фигарить -_-. Не смог ТСу доказать, что WithStore и Component - typeof Block.

2021-10-10 17:10 UTC, nickchamel approved these changes
Отлично. Работу принял. Успехов в дальнейшем!

2021-10-10 17:10 UTC, nickchamel commented on src/common/Router/Route.ts
> +  private block: Block<{}> | null;
Ну по сути Block<any, any>
Сюда любой класс может прийти в конструктор. Знаем только то, что он экстендится от блока, а с какими пропсами и тд мы не может знать. А писать для них общий абстрактный интерфейс это такое себе...

2021-10-10 17:10 UTC, nickchamel commented on src/pages/messenger/messenger.ts
> +  onChatChoose: (userId: number, chat: IChat, toke: string) => void;
`tokeN`

2021-10-10 17:10 UTC, nickchamel commented on src/common/Block/Block.ts
> +    }, 1);
Это всеравно сайд-эффект) метод getContent должен просто вернуть контент. Логически. Семантически...
Подумай над тем, что может быть в другое место сайдэффект перенести. CDM у нас ведь где должен быть? После рендера компонента, когда мы скомпилили шаблон и вставили его в this.element

2021-10-10 17:16 UTC, Tenutes commented on src/common/Router/Route.ts
> +  private block: Block<{}> | null;
Понял.

2021-10-10 17:16 UTC, Tenutes commented on src/pages/messenger/messenger.ts
> +  onChatChoose: (userId: number, chat: IChat, toke: string) => void;
Упс)

2021-10-10 17:17 UTC, Tenutes commented on src/common/Block/Block.ts
> +    }, 1);
Да, я тут абсолютно согласен, к сожалению, пока вермени немного работаь над проектом. И мне так быстро не пришло в голову, в каком момент эмить CDM из BLOCK, ибо рендерится главный в Роутере, а children - в Block. И что единственно общего у этих двух мест - getContent. Буду думать, как этот момент переделать.

2021-10-10 17:21 UTC, merged